### PR TITLE
change tesnet network 

### PR DESCRIPTION
**Pull request by MrSahilShaikh**
testnet network change to sepolia testnet
#39 

## Title

Testnet network change to sepolia testnet

## Proposed Changes

changes done in hardhatconfig file, & deployed it 

## Check List (Check all the applicable boxes)

- [ ] Bug(s) fixed
- [x] Enhancement done
- [x] New Feature(s) added
- [ ] Documentation changed
- [x] All new and existing tests passed.
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by LakshaySK106** [comment]
Have you tested this code till all the endpoints?

**Comment by LakshaySK106** [comment]
I think this gonna create errors while deploying it to the thirdWeb

**Comment by MrSahilShaikh** [comment]
yes i deployed it on thirdweb. deployed address 0xdafb4058Fe2b48Dc0965A3313B7F8173e49eC59d on thirdweb
you can also check on etherscan
@LakshaySK106

**Comment by MrSahilShaikh** [comment]
are you trying to create new campaign from front end? @LakshaySK106

**Comment by LakshaySK106** [comment]
Yes @MrSahilShaikh

**Pull request closed without merging**
