### PR TITLE
All Pages work responsive on mobile devices issue#105 resolved

### PR DESCRIPTION
**Pull request by Geeta259**
#105 

## Proposed Changes

Website Pages work fine on mobile devices now!!

## Check List (Check all the applicable boxes)

- [ ] Bug(s) fixed
- [ x] Enhancement done
- [ x] New Feature(s) added
- [ ] Documentation changed
- [ x] All new and existing tests passed.
- [ x] My code follows the code style of this project.

## Screenshots (if any)
Screenshot (439)

Screenshot (440)

Screenshot (442)

Screenshot (444)

Screenshot (445)

@LakshaySK106 issue#105 Please review it !!

### CODE REVIEW

**Comment by LakshaySK106** [comment]
The sidebar is occupying too much space. Wouldn't it be much better if we could hide it with the hamburger icon? @Geeta259

**Comment by Geeta259** [comment]
@LakshaySK106 yeah sure!! I try.

**Comment by Geeta259** [comment]
@LakshaySK106 Please review this PR#128

**Comment by LakshaySK106** [comment]
Redundant PR with #128

**Pull request closed without merging**
