### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ayush-Tibrewal**
added new look please check

### CODE REVIEW

**Comment by Ayush-Tibrewal** [comment]
hii @amitbatra31  please tell if you have any issue thank you

**Comment by LakshaySK106** [comment]
changes are not remarkable

**Comment by Ayush-Tibrewal** [comment]
@LakshaySK106  working on it and assist if you can

**Comment by Venkatakrishnan-Ramesh** [comment]
@Ayush-Tibrewal  Kindly look into some other contribution since this is already done . We are closing this

**Pull request closed without merging**
