### PR TITLE
Added SearchBar Function (Issue #2)

### PR DESCRIPTION
**Pull request by KandepiBhavani23**
Added a Search Function where user will able to filter out the Campaign Cards based on the given input in the search-bar.
PLease review it once

image

### CODE REVIEW

**Comment by LakshaySK106** [comment]
you've altered too many files unnecessarily. However, the changes should be done in the "navBar" component only. Can you please make another commit with only the necessary changes? It's difficult for me to figure it out or I might lose the valuable changes.

**Comment by KandepiBhavani23** [comment]
In order to address the required modifications, it is necessary to make changes not only to the navbar component but also to the home component. This is because the navbar contains the search bar, and the display of campaign cards is specifically handled in the home component. Therefore, the alterations need to be implemented across both components to achieve the desired outcome.

Please provide your inputs here so that I can modify it accordingly

**Comment by LakshaySK106** [comment]
I see that major modifications have been done to the navBar component. Additionally, with the home component, it can be observed that the other files are changed coz of the formatting of the source code. Im deleting the other files from the commit and considering the alterations made in the navbar and home component only.

If you'd like to make another commit with these two files gonna work well or I can delete them at my end.
REST LOOKS GOOD!👍

**Comment by KandepiBhavani23** [comment]
Absolutely correct. The changes were made only in Navbar and Home Component and in rest all components its just a formatting of source code . You can delete the rest of the files.

Thanks!!

**Comment by LakshaySK106** [comment]
Thank you for your contributions!

**Pull request merged**
