### PR TITLE
A better and more attractive Landing page. [ Fixes Issue - #48 ]

### PR DESCRIPTION
**Pull request by BaibhavTiwari**
Fixes Issue - #48

## Title
A better and more attractive Landing page.

## Proposed Changes
Created a more attractive Landing page then the previous one, which was quite simple and basic.
which is not making much difference and led to less engagement of the traffic.

## Check List (Check all the applicable boxes)

- [x] Bug(s) fixed
- [x] Enhancement done
- [x] New Feature(s) added
- [ ] Documentation changed
- [x] All new and existing tests passed.
- [x] My code follows the code style of this project.

## Screenshots (if any)

image

### CODE REVIEW

**Comment by Venkatakrishnan-Ramesh** [comment]
@BaibhavTiwari  The design is neat and clean , will there be hover effect over image icon when you move your mouse pointer

**Comment by BaibhavTiwari** [comment]
> @BaibhavTiwari The design is neat and clean , will there be hover effect over image icon when you move your mouse pointer

till now there is no hover effect on the images, I can add it if you want!!

**Comment by Venkatakrishnan-Ramesh** [comment]
Kindly add it , it may look even more better

**Comment by BaibhavTiwari** [comment]
> Kindly add it , it may look even more better

added the `hover:rotate-12` class is added to the `img` elements. which applies a rotation transformation of 12 degrees when hovered over, creating a rotating effect.

**Review by LakshaySK106 — APPROVED** [review]

**Comment by LakshaySK106** [comment]
Amazing work! Thank you @BaibhavTiwari for your valuable contributions.

**Pull request merged**
