### PR TITLE
Created Github Workflow that auto commit 

### PR DESCRIPTION
**Pull request by Nishitbaria**
**I have created a Workflow that automatically commits when an issue is opened, a pull request is created, an issue is closed, or an issue is assigned or unassigned.** 

 **`The issue number that resolves this particular issue is`:https://github.com/group-patronage/group-patronage/issues/60**

### CODE REVIEW

**Comment by Nishitbaria** [comment]
To run this Workflow you have to able to permission into the Repository setting 
image

**Comment by LakshaySK106** [comment]
Changed the workflow permissions. Thank you for your contributions!

**Comment by LakshaySK106** [comment]
Screenshot 2023-06-04 at 9 56 41 AM

**Comment by LakshaySK106** [comment]
hey @Nishitbaria, the template is not working and I'm too not able to allow these permissions as you can see below.

**Comment by LakshaySK106** [comment]
Screenshot 2023-06-04 at 9 58 26 AM

**Comment by LakshaySK106** [comment]
the checkbox is not allowing^

**Comment by Nishitbaria** [comment]
Hey @LakshaySK106  The repo owner  only able to give this permission

**Comment by Nishitbaria** [comment]
Please Give to read write access please checkmark the first checkbox

**Comment by LakshaySK106** [comment]
I gave all the necessary permissions and it's working now. Thank you!

**Comment by Nishitbaria** [comment]
hey @LakshaySK106  please add the Gssoc label and the level 3 label without this it not count in Gsso2023 Leaderboard

**Pull request merged**
