### PR TITLE
Added Responsive Design to Website for Smaller Devices

### PR DESCRIPTION
**Pull request by abhijeetnishal**
## Title
Making the website Responsive for Smaller Devices which is lacking.
Closes: #18 

## Proposed Changes
Added breakpoint of min-width:300px and added styling that makes the website more responsive.
Added responsiveness in landing page, Home page, survey page, campaign page.

## Check List (Check all the applicable boxes)

[x] Enhancement done
[x] My code follows the code style of this project.

## Screenshots (if any)
Screenshot 2023-05-29 at 11 35 41 PM
Screenshot 2023-05-29 at 11 35 56 PM
Screenshot 2023-05-29 at 11 36 12 PM
Screenshot 2023-05-29 at 11 36 43 PM

### CODE REVIEW

**Comment by LakshaySK106** [comment]
In the small-sized screens, the sidebar should be hidden and added to the hamburger menu icon otherwise it takes too much space and the campaigns looks congested.

**Comment by AK4266** [comment]
Hey, I would like to work on the issue. Can you assign it to me?

**Comment by Venkatakrishnan-Ramesh** [comment]
@abhijeetnishal  kindly check the conflict and proceed to pull request again

**Comment by abhijeetnishal** [comment]
### Removed side navbar for smaller devices and making it more visible in smaller devices for better user experience.

## Screenshots:
Screenshot 2023-06-25 at 3 05 09 PM
Screenshot 2023-06-25 at 3 05 26 PM

**Comment by LakshaySK106** [comment]
Thank you for your contributions!

**Pull request merged**
